### ISSUE TITLE
似乎淘宝联盟的cookie会失效

### ISSUE THREAD

**Issue by imyip** [xsren/wx_taobao_fanli#1] opened 2017-07-22 04:58 UTC
似乎淘宝联盟的cookie会失效

**Comment by xsren** [comment] 2017-07-22 05:47
多久失效？cookie一般都有生命周期的。

**Comment by imyip** [comment] 2017-07-22 10:37
一段时间吧,具体不是很清楚.会报以下代码.
`{"data":null,"info":{"message":"nologin","ok":false},"ok":false,"invalidKey":null}
'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/root/wx_taobao_fanli/libs/alimama.py", line 239, in get_tk_link
    gcid, siteid, adzoneid = self.__get_tk_link_s1(auctionid, tb_token, pvid)
  File "/root/wx_taobao_fanli/libs/alimama.py", line 265, in __get_tk_link_s1
    gcid = rj['data']['otherList'][0]['gcid']
TypeError: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "/root/wx_taobao_fanli/libs/wx_bot.py", line 48, in check_if_is_tb_link
    tao_token = res1['taoToken']
TypeError: string indices must be integers, not str`

**Comment by xsren** [comment] 2017-07-23 04:28
cookie过期，这个只能重新登录

**Comment by xsren** [comment] 2017-09-19 08:53
Duplicate of #2

**Closed** 2017-09-19 08:53 UTC
